full_score=float(input("Input Full Score="))
real_score=float(input("Input Real Score="))
percentage=real_score*100/full_score
print("---------------------------")
print("----Calculate Percentage---")
print("---------------------------")
print("Full Score:%.2f" %(full_score))
print("real Score:%.2f" %(real_score))
print("---------------------------")
print("Percentage: %.2f%%" %(percentage))
print("---------------------------")
